version: "3.9"
services:
  trade-service-postgres:
    container_name: trade-service-postgres
    image: "postgres:13.4-alpine"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
